# Generated by Django 4.1.1 on 2022-10-07 12:34

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='site_logo',
            field=models.ImageField(default=1, help_text='Should be a small icon', upload_to=main.models.Main.get_file_name),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='main',
            name='site_title',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
