# Generated by Django 4.1.1 on 2022-10-07 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_main_site_logo_main_site_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('position',), 'verbose_name_plural': 'Products'},
        ),
        migrations.RenameField(
            model_name='main',
            old_name='line2',
            new_name='line_2',
        ),
    ]
