# Generated by Django 4.1.1 on 2022-10-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_products_options_rename_line2_main_line_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='about_text_en',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='about_text_uk',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='address_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='address_uk',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='tel_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='tel_uk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='title_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='title_uk',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='intro_message_1_en',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='intro_message_1_uk',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='intro_message_2_en',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='intro_message_2_uk',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='line_1_en',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='line_1_uk',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='line_2_en',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='line_2_uk',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='site_title_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='site_title_uk',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='description_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='description_uk',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='name_en',
            field=models.CharField(db_index=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='name_uk',
            field=models.CharField(db_index=True, max_length=300, null=True),
        ),
    ]
