# Generated by Django 4.1.1 on 2022-12-21 20:25

import ckeditor.fields
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_about_about_text_en_about_about_text_uk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_text',
            field=ckeditor.fields.RichTextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='about',
            name='about_text_en',
            field=ckeditor.fields.RichTextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='about_text_uk',
            field=ckeditor.fields.RichTextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='address',
            field=ckeditor.fields.RichTextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='address_en',
            field=ckeditor.fields.RichTextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='address_uk',
            field=ckeditor.fields.RichTextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='tel',
            field=ckeditor.fields.RichTextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='tel_en',
            field=ckeditor.fields.RichTextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='tel_uk',
            field=ckeditor.fields.RichTextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='title',
            field=ckeditor.fields.RichTextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='title_en',
            field=ckeditor.fields.RichTextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='title_uk',
            field=ckeditor.fields.RichTextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='intro_message_1',
            field=ckeditor.fields.RichTextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='home',
            name='intro_message_1_en',
            field=ckeditor.fields.RichTextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='intro_message_1_uk',
            field=ckeditor.fields.RichTextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='intro_message_2',
            field=ckeditor.fields.RichTextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='home',
            name='intro_message_2_en',
            field=ckeditor.fields.RichTextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='intro_message_2_uk',
            field=ckeditor.fields.RichTextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='products',
            name='description_en',
            field=ckeditor.fields.RichTextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='description_uk',
            field=ckeditor.fields.RichTextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=ckeditor.fields.RichTextField(db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='products',
            name='name_en',
            field=ckeditor.fields.RichTextField(db_index=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='name_uk',
            field=ckeditor.fields.RichTextField(db_index=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='photo',
            field=models.ImageField(help_text='recommended resolution 600-900px ', upload_to=main.models.Products.get_file_name),
        ),
    ]
